module.exports = Object.freeze({
    FACEBOOK: "facebook",
    ALEXA: "alexa",
    CHAT:"chat",
    IVR:"ivr",
    GOOGLE:"google",
    CONTINUEWITHBOT:"ContinueWithBot",
    FBENDPOINT:"https://graph.facebook.com/v2.6/me/messages",
    NOW:"now",
    REGISTRATIONNUMBER:"registrationNumber",




    DEPARTING_STATION:'departing-station',
    DESTINATION_STATION:'destination-station',
    DEPART_DATETIME:'depart-datetime',
    DATETIME:'date-time',
    DIALOG_CONTEXT:'dialog_context',
    ZERO:0,
    RESPONSE_TEXT:'text',
    RESPONSE_OPTIONS:'options',
    RESPONSE_CAROUSEL:'carousel',
    RESPONSE_ERROR:'error',
    NO_JOURNEY:"Snap!!! I couldn't find any journey. Let's try again!!!",
    GOOGLE_POSSIBLE_INTENTS:'}},"possibleIntents": [{"intent": "actions.intent.TEXT"}]}]}',
    LOGO_ALT_TEXT:"Logo",
    BOOK_JOURNEY:"Book This Journey",
    ERROR_MSG:"Sorry, we are facing some technical issues, we will be back shortly",
    SERVICE_HOME_PAGE : process.env.SERVICE_HOME_PAGE || "http://www.redspottedhanky.com/",
    SERVICE_LOGO_URL: process.env.SERVICE_LOGO_URL || 'http://rshplanner-prod.eu-west-1.elasticbeanstalk.com/RSHLogo.png',
    SERVICE_FAQ_URL : process.env.SERVICE_FAQ_URL || 'http://www.redspottedhanky.com/frequently-asked-questions/',
    SERVICE_CONTACT_US_URL : process.env.SERVICE_CONTACT_US_URL || 'http://www.redspottedhanky.com/contact-us/contact-us-about-booking/',
    DESTINATIONSTATION:"DESTINATIONSTATION",
    EXACT_MATCH:"EXACT_MATCH",
    DEPARTINGSTATION: "DEPARTINGSTATION",
    ANYSTATION:"ANYSTATION",
    DATESLOT:"dateslot",
    DEPART_DATE:"DEPART_DATE",
    TIMESLOT:"timeslot",
    DEPART_TIME:"DEPART_TIME",
    CATCHSLOT:"catch",
    OPERATOR_NAMES:", ",
    LOGO_BASE_PATH:process.env.LOGO_BASE_PATH || "http://localhost:3000/logos/",
    MERGED_LOGO_PATH:process.env.MERGED_LOGO_PATH || "http://localhost:3000/tempLogos/",
    MERGED_IMAGE_PATH:"public/tempLogos/",
    MERGED_IMAGE_PREFIX:"merged",
    MERGED_IMAGE_MIME:".png",
    NEXT_JOURNEY:"NEXT_JOURNEY",
    TIMEZONE: process.env.TIMEZONE || "Europe/London",
    SHOW_DETAILS:"show.Details",
    MESSAGES_NEWLINE:"\n"
});
